log:
  # see: vendor/github.com/sirupsen/logrus/logrus.go
  # 0 - PanicLevel
  # 1 - FatalLevel
  # 2 - ErrorLevel
  # 3 - WarnLevel
  # 4 - InfoLevel
  # 5 - DebugLevel
  # 6 - TraceLevel
  level: 4

db:
  host: db
  port: 5432
  name: postgres
  user: postgres
  password: postgres

httpServer:
  port: 80
  # see: vendor/github.com/gin-gonic/gin/mode.go
  # debug
  # release
  # test
  mode: release

canceller:
  cancelTransactionsCount: 10
  repeatCancellationEveryMinutes: 0.5
